import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { getToken } from "../lib/auth";

const STATES = { IDLE: "idle", EDITING: "editing", PUBLISHING: "publishing" };
export function PostEditor() {
  const [status, setStatus] = useState(STATES.IDLE); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [errorMessage, setErrorMessage] = useState(null); const navigate = useNavigate();
  async function handlePublish(event) { event.preventDefault(); setStatus(STATES.PUBLISHING); setErrorMessage(null); try { const response = await fetch("/api/posts", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${getToken() || ""}` }, body: JSON.stringify({ title, body }) }); const data = await response.json(); if (!response.ok) { setErrorMessage(data.error?.message || "Could not publish the post."); setStatus(STATES.EDITING); return; } navigate("/"); } catch { setErrorMessage("Something went wrong. Please try again."); setStatus(STATES.EDITING); } }
  return <form className="space-y-4" onSubmit={handlePublish}><h1 className="text-2xl font-bold">Write a post</h1><div><label htmlFor="post-title" className="block text-sm font-medium">Title</label><input id="post-title" required value={title} onChange={(e) => { setTitle(e.target.value); setStatus(STATES.EDITING); }} className="mt-1 block w-full rounded border border-gray-300 p-2" aria-describedby={errorMessage ? "post-error" : undefined} /></div><div><label htmlFor="post-body" className="block text-sm font-medium">Body</label><textarea id="post-body" required value={body} onChange={(e) => { setBody(e.target.value); setStatus(STATES.EDITING); }} rows="10" className="mt-1 block w-full rounded border border-gray-300 p-2" /></div>{errorMessage && <p id="post-error" role="alert" className="text-sm text-red-600">{errorMessage}</p>}<button type="submit" disabled={status === STATES.PUBLISHING} className="rounded bg-indigo-600 px-4 py-2 text-white disabled:opacity-50">{status === STATES.PUBLISHING ? "Publishing..." : "Publish"}</button></form>;
}
